# Generated by Django 4.0.5 on 2022-06-26 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Aduana',
            fields=[
                ('id_aduana', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_aduana', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_user', models.CharField(max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_user', models.CharField(max_length=10)),
                ('deleted_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'aduana',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_cliente', models.CharField(max_length=20)),
                ('apellido_cliente', models.CharField(max_length=20)),
                ('dui_cliente', models.IntegerField()),
                ('nit_cliente', models.IntegerField()),
                ('direccion_cliente', models.CharField(max_length=20)),
                ('empresa', models.CharField(max_length=20)),
                ('telefono_cliente', models.IntegerField()),
                ('genero', models.CharField(max_length=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_user', models.CharField(max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_user', models.CharField(max_length=10)),
                ('deleted_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'cliente',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_departamento', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombre_departamento', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_user', models.CharField(max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_user', models.CharField(max_length=10)),
                ('deleted_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'departamento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Transportista',
            fields=[
                ('id_transportista', models.IntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_user', models.CharField(max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_user', models.CharField(max_length=10)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='aduana_api.cliente')),
            ],
            options={
                'db_table': 'transportista',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('id_transporte', models.IntegerField(primary_key=True, serialize=False)),
                ('numero_vin', models.CharField(max_length=17)),
                ('numero_motor', models.CharField(max_length=10)),
                ('numero_chasis', models.CharField(max_length=17)),
                ('ano', models.IntegerField()),
                ('marca', models.CharField(max_length=10)),
                ('capacidad_maxima', models.FloatField()),
                ('modelo', models.CharField(max_length=10)),
                ('numero_placas', models.CharField(max_length=7)),
                ('procedencia', models.CharField(max_length=10)),
                ('destino', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_user', models.CharField(max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_user', models.CharField(max_length=10)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='aduana_api.cliente')),
            ],
            options={
                'db_table': 'transporte',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id_municipio', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombre_municipio', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_user', models.CharField(max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_user', models.CharField(max_length=10)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('id_departamento', models.ForeignKey(db_column='id_departamento', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='aduana_api.departamento')),
            ],
            options={
                'db_table': 'municipio',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Carga',
            fields=[
                ('id_carga', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=10)),
                ('peso', models.FloatField()),
                ('descripcion', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_user', models.CharField(max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_user', models.CharField(max_length=10)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('id_transporte', models.ForeignKey(db_column='id_transporte', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='aduana_api.transporte')),
            ],
            options={
                'db_table': 'carga',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id_archivo', models.IntegerField(primary_key=True, serialize=False)),
                ('numero_registro', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_user', models.CharField(max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_user', models.CharField(max_length=10)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('id_aduana', models.ForeignKey(db_column='id_aduana', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='aduana_api.aduana')),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='aduana_api.cliente')),
                ('id_municipio', models.ForeignKey(db_column='id_municipio', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='aduana_api.municipio')),
            ],
            options={
                'db_table': 'archivo',
                'managed': True,
            },
        ),
    ]
