# Generated by Django 4.0.5 on 2022-06-27 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aduana_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='id_carga',
            field=models.ForeignKey(db_column='id_carga', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='aduana_api.carga'),
        ),
    ]
