# Generated by Django 4.0.5 on 2022-06-27 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aduana_api', '0002_archivo_id_carga'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='aprobado',
            field=models.BooleanField(default=False),
        ),
    ]
